language: python
python:
  - "3.5"
  - "3.8"
env:
  - DJANGO="master"
  - DJANGO="22"
matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: DJANGO="22"
    - python: "3.8"
      env: DJANGO="22"
  allow_failures:
    - env: DJANGO="master"
install:
  - pip install --upgrade pip setuptools tox
script:
  - tox -e py$(python -c 'import sys;print("{0}{1}".format(*sys.version_info))')-dj${DJANGO}
notifications:
  irc: "irc.freenode.org#mezzanine"
  on_success: change
  on_failure: change
